package com.example.acceptance2.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.acceptance2.greendao.bean.AcceptDeviceBean;
import com.example.acceptance2.greendao.bean.ApplyDeptBean;
import com.example.acceptance2.greendao.bean.ApplyItemBean;
import com.example.acceptance2.greendao.bean.CheckApplyBean;
import com.example.acceptance2.greendao.bean.CheckFileBean;
import com.example.acceptance2.greendao.bean.CheckGroupBean;
import com.example.acceptance2.greendao.bean.CheckItemBean;
import com.example.acceptance2.greendao.bean.CheckItemRelateBean;
import com.example.acceptance2.greendao.bean.CheckTaskBean;
import com.example.acceptance2.greendao.bean.CheckUnresolvedBean;
import com.example.acceptance2.greendao.bean.CheckVerdBean;
import com.example.acceptance2.greendao.bean.DataPackageDBean;
import com.example.acceptance2.greendao.bean.DeliveryListBean;
import com.example.acceptance2.greendao.bean.DocumentBean;
import com.example.acceptance2.greendao.bean.FileBean;
import com.example.acceptance2.greendao.bean.PropertyBean;
import com.example.acceptance2.greendao.bean.PropertyBeanX;
import com.example.acceptance2.greendao.bean.RegisterBean;
import com.example.acceptance2.greendao.bean.RelatedDocumentIdSetBean;
import com.example.acceptance2.greendao.bean.TestTabBean;
import com.example.acceptance2.greendao.bean.UnresolvedBean;

import com.example.acceptance2.greendao.db.AcceptDeviceBeanDao;
import com.example.acceptance2.greendao.db.ApplyDeptBeanDao;
import com.example.acceptance2.greendao.db.ApplyItemBeanDao;
import com.example.acceptance2.greendao.db.CheckApplyBeanDao;
import com.example.acceptance2.greendao.db.CheckFileBeanDao;
import com.example.acceptance2.greendao.db.CheckGroupBeanDao;
import com.example.acceptance2.greendao.db.CheckItemBeanDao;
import com.example.acceptance2.greendao.db.CheckItemRelateBeanDao;
import com.example.acceptance2.greendao.db.CheckTaskBeanDao;
import com.example.acceptance2.greendao.db.CheckUnresolvedBeanDao;
import com.example.acceptance2.greendao.db.CheckVerdBeanDao;
import com.example.acceptance2.greendao.db.DataPackageDBeanDao;
import com.example.acceptance2.greendao.db.DeliveryListBeanDao;
import com.example.acceptance2.greendao.db.DocumentBeanDao;
import com.example.acceptance2.greendao.db.FileBeanDao;
import com.example.acceptance2.greendao.db.PropertyBeanDao;
import com.example.acceptance2.greendao.db.PropertyBeanXDao;
import com.example.acceptance2.greendao.db.RegisterBeanDao;
import com.example.acceptance2.greendao.db.RelatedDocumentIdSetBeanDao;
import com.example.acceptance2.greendao.db.TestTabBeanDao;
import com.example.acceptance2.greendao.db.UnresolvedBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig acceptDeviceBeanDaoConfig;
    private final DaoConfig applyDeptBeanDaoConfig;
    private final DaoConfig applyItemBeanDaoConfig;
    private final DaoConfig checkApplyBeanDaoConfig;
    private final DaoConfig checkFileBeanDaoConfig;
    private final DaoConfig checkGroupBeanDaoConfig;
    private final DaoConfig checkItemBeanDaoConfig;
    private final DaoConfig checkItemRelateBeanDaoConfig;
    private final DaoConfig checkTaskBeanDaoConfig;
    private final DaoConfig checkUnresolvedBeanDaoConfig;
    private final DaoConfig checkVerdBeanDaoConfig;
    private final DaoConfig dataPackageDBeanDaoConfig;
    private final DaoConfig deliveryListBeanDaoConfig;
    private final DaoConfig documentBeanDaoConfig;
    private final DaoConfig fileBeanDaoConfig;
    private final DaoConfig propertyBeanDaoConfig;
    private final DaoConfig propertyBeanXDaoConfig;
    private final DaoConfig registerBeanDaoConfig;
    private final DaoConfig relatedDocumentIdSetBeanDaoConfig;
    private final DaoConfig testTabBeanDaoConfig;
    private final DaoConfig unresolvedBeanDaoConfig;

    private final AcceptDeviceBeanDao acceptDeviceBeanDao;
    private final ApplyDeptBeanDao applyDeptBeanDao;
    private final ApplyItemBeanDao applyItemBeanDao;
    private final CheckApplyBeanDao checkApplyBeanDao;
    private final CheckFileBeanDao checkFileBeanDao;
    private final CheckGroupBeanDao checkGroupBeanDao;
    private final CheckItemBeanDao checkItemBeanDao;
    private final CheckItemRelateBeanDao checkItemRelateBeanDao;
    private final CheckTaskBeanDao checkTaskBeanDao;
    private final CheckUnresolvedBeanDao checkUnresolvedBeanDao;
    private final CheckVerdBeanDao checkVerdBeanDao;
    private final DataPackageDBeanDao dataPackageDBeanDao;
    private final DeliveryListBeanDao deliveryListBeanDao;
    private final DocumentBeanDao documentBeanDao;
    private final FileBeanDao fileBeanDao;
    private final PropertyBeanDao propertyBeanDao;
    private final PropertyBeanXDao propertyBeanXDao;
    private final RegisterBeanDao registerBeanDao;
    private final RelatedDocumentIdSetBeanDao relatedDocumentIdSetBeanDao;
    private final TestTabBeanDao testTabBeanDao;
    private final UnresolvedBeanDao unresolvedBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        acceptDeviceBeanDaoConfig = daoConfigMap.get(AcceptDeviceBeanDao.class).clone();
        acceptDeviceBeanDaoConfig.initIdentityScope(type);

        applyDeptBeanDaoConfig = daoConfigMap.get(ApplyDeptBeanDao.class).clone();
        applyDeptBeanDaoConfig.initIdentityScope(type);

        applyItemBeanDaoConfig = daoConfigMap.get(ApplyItemBeanDao.class).clone();
        applyItemBeanDaoConfig.initIdentityScope(type);

        checkApplyBeanDaoConfig = daoConfigMap.get(CheckApplyBeanDao.class).clone();
        checkApplyBeanDaoConfig.initIdentityScope(type);

        checkFileBeanDaoConfig = daoConfigMap.get(CheckFileBeanDao.class).clone();
        checkFileBeanDaoConfig.initIdentityScope(type);

        checkGroupBeanDaoConfig = daoConfigMap.get(CheckGroupBeanDao.class).clone();
        checkGroupBeanDaoConfig.initIdentityScope(type);

        checkItemBeanDaoConfig = daoConfigMap.get(CheckItemBeanDao.class).clone();
        checkItemBeanDaoConfig.initIdentityScope(type);

        checkItemRelateBeanDaoConfig = daoConfigMap.get(CheckItemRelateBeanDao.class).clone();
        checkItemRelateBeanDaoConfig.initIdentityScope(type);

        checkTaskBeanDaoConfig = daoConfigMap.get(CheckTaskBeanDao.class).clone();
        checkTaskBeanDaoConfig.initIdentityScope(type);

        checkUnresolvedBeanDaoConfig = daoConfigMap.get(CheckUnresolvedBeanDao.class).clone();
        checkUnresolvedBeanDaoConfig.initIdentityScope(type);

        checkVerdBeanDaoConfig = daoConfigMap.get(CheckVerdBeanDao.class).clone();
        checkVerdBeanDaoConfig.initIdentityScope(type);

        dataPackageDBeanDaoConfig = daoConfigMap.get(DataPackageDBeanDao.class).clone();
        dataPackageDBeanDaoConfig.initIdentityScope(type);

        deliveryListBeanDaoConfig = daoConfigMap.get(DeliveryListBeanDao.class).clone();
        deliveryListBeanDaoConfig.initIdentityScope(type);

        documentBeanDaoConfig = daoConfigMap.get(DocumentBeanDao.class).clone();
        documentBeanDaoConfig.initIdentityScope(type);

        fileBeanDaoConfig = daoConfigMap.get(FileBeanDao.class).clone();
        fileBeanDaoConfig.initIdentityScope(type);

        propertyBeanDaoConfig = daoConfigMap.get(PropertyBeanDao.class).clone();
        propertyBeanDaoConfig.initIdentityScope(type);

        propertyBeanXDaoConfig = daoConfigMap.get(PropertyBeanXDao.class).clone();
        propertyBeanXDaoConfig.initIdentityScope(type);

        registerBeanDaoConfig = daoConfigMap.get(RegisterBeanDao.class).clone();
        registerBeanDaoConfig.initIdentityScope(type);

        relatedDocumentIdSetBeanDaoConfig = daoConfigMap.get(RelatedDocumentIdSetBeanDao.class).clone();
        relatedDocumentIdSetBeanDaoConfig.initIdentityScope(type);

        testTabBeanDaoConfig = daoConfigMap.get(TestTabBeanDao.class).clone();
        testTabBeanDaoConfig.initIdentityScope(type);

        unresolvedBeanDaoConfig = daoConfigMap.get(UnresolvedBeanDao.class).clone();
        unresolvedBeanDaoConfig.initIdentityScope(type);

        acceptDeviceBeanDao = new AcceptDeviceBeanDao(acceptDeviceBeanDaoConfig, this);
        applyDeptBeanDao = new ApplyDeptBeanDao(applyDeptBeanDaoConfig, this);
        applyItemBeanDao = new ApplyItemBeanDao(applyItemBeanDaoConfig, this);
        checkApplyBeanDao = new CheckApplyBeanDao(checkApplyBeanDaoConfig, this);
        checkFileBeanDao = new CheckFileBeanDao(checkFileBeanDaoConfig, this);
        checkGroupBeanDao = new CheckGroupBeanDao(checkGroupBeanDaoConfig, this);
        checkItemBeanDao = new CheckItemBeanDao(checkItemBeanDaoConfig, this);
        checkItemRelateBeanDao = new CheckItemRelateBeanDao(checkItemRelateBeanDaoConfig, this);
        checkTaskBeanDao = new CheckTaskBeanDao(checkTaskBeanDaoConfig, this);
        checkUnresolvedBeanDao = new CheckUnresolvedBeanDao(checkUnresolvedBeanDaoConfig, this);
        checkVerdBeanDao = new CheckVerdBeanDao(checkVerdBeanDaoConfig, this);
        dataPackageDBeanDao = new DataPackageDBeanDao(dataPackageDBeanDaoConfig, this);
        deliveryListBeanDao = new DeliveryListBeanDao(deliveryListBeanDaoConfig, this);
        documentBeanDao = new DocumentBeanDao(documentBeanDaoConfig, this);
        fileBeanDao = new FileBeanDao(fileBeanDaoConfig, this);
        propertyBeanDao = new PropertyBeanDao(propertyBeanDaoConfig, this);
        propertyBeanXDao = new PropertyBeanXDao(propertyBeanXDaoConfig, this);
        registerBeanDao = new RegisterBeanDao(registerBeanDaoConfig, this);
        relatedDocumentIdSetBeanDao = new RelatedDocumentIdSetBeanDao(relatedDocumentIdSetBeanDaoConfig, this);
        testTabBeanDao = new TestTabBeanDao(testTabBeanDaoConfig, this);
        unresolvedBeanDao = new UnresolvedBeanDao(unresolvedBeanDaoConfig, this);

        registerDao(AcceptDeviceBean.class, acceptDeviceBeanDao);
        registerDao(ApplyDeptBean.class, applyDeptBeanDao);
        registerDao(ApplyItemBean.class, applyItemBeanDao);
        registerDao(CheckApplyBean.class, checkApplyBeanDao);
        registerDao(CheckFileBean.class, checkFileBeanDao);
        registerDao(CheckGroupBean.class, checkGroupBeanDao);
        registerDao(CheckItemBean.class, checkItemBeanDao);
        registerDao(CheckItemRelateBean.class, checkItemRelateBeanDao);
        registerDao(CheckTaskBean.class, checkTaskBeanDao);
        registerDao(CheckUnresolvedBean.class, checkUnresolvedBeanDao);
        registerDao(CheckVerdBean.class, checkVerdBeanDao);
        registerDao(DataPackageDBean.class, dataPackageDBeanDao);
        registerDao(DeliveryListBean.class, deliveryListBeanDao);
        registerDao(DocumentBean.class, documentBeanDao);
        registerDao(FileBean.class, fileBeanDao);
        registerDao(PropertyBean.class, propertyBeanDao);
        registerDao(PropertyBeanX.class, propertyBeanXDao);
        registerDao(RegisterBean.class, registerBeanDao);
        registerDao(RelatedDocumentIdSetBean.class, relatedDocumentIdSetBeanDao);
        registerDao(TestTabBean.class, testTabBeanDao);
        registerDao(UnresolvedBean.class, unresolvedBeanDao);
    }
    
    public void clear() {
        acceptDeviceBeanDaoConfig.clearIdentityScope();
        applyDeptBeanDaoConfig.clearIdentityScope();
        applyItemBeanDaoConfig.clearIdentityScope();
        checkApplyBeanDaoConfig.clearIdentityScope();
        checkFileBeanDaoConfig.clearIdentityScope();
        checkGroupBeanDaoConfig.clearIdentityScope();
        checkItemBeanDaoConfig.clearIdentityScope();
        checkItemRelateBeanDaoConfig.clearIdentityScope();
        checkTaskBeanDaoConfig.clearIdentityScope();
        checkUnresolvedBeanDaoConfig.clearIdentityScope();
        checkVerdBeanDaoConfig.clearIdentityScope();
        dataPackageDBeanDaoConfig.clearIdentityScope();
        deliveryListBeanDaoConfig.clearIdentityScope();
        documentBeanDaoConfig.clearIdentityScope();
        fileBeanDaoConfig.clearIdentityScope();
        propertyBeanDaoConfig.clearIdentityScope();
        propertyBeanXDaoConfig.clearIdentityScope();
        registerBeanDaoConfig.clearIdentityScope();
        relatedDocumentIdSetBeanDaoConfig.clearIdentityScope();
        testTabBeanDaoConfig.clearIdentityScope();
        unresolvedBeanDaoConfig.clearIdentityScope();
    }

    public AcceptDeviceBeanDao getAcceptDeviceBeanDao() {
        return acceptDeviceBeanDao;
    }

    public ApplyDeptBeanDao getApplyDeptBeanDao() {
        return applyDeptBeanDao;
    }

    public ApplyItemBeanDao getApplyItemBeanDao() {
        return applyItemBeanDao;
    }

    public CheckApplyBeanDao getCheckApplyBeanDao() {
        return checkApplyBeanDao;
    }

    public CheckFileBeanDao getCheckFileBeanDao() {
        return checkFileBeanDao;
    }

    public CheckGroupBeanDao getCheckGroupBeanDao() {
        return checkGroupBeanDao;
    }

    public CheckItemBeanDao getCheckItemBeanDao() {
        return checkItemBeanDao;
    }

    public CheckItemRelateBeanDao getCheckItemRelateBeanDao() {
        return checkItemRelateBeanDao;
    }

    public CheckTaskBeanDao getCheckTaskBeanDao() {
        return checkTaskBeanDao;
    }

    public CheckUnresolvedBeanDao getCheckUnresolvedBeanDao() {
        return checkUnresolvedBeanDao;
    }

    public CheckVerdBeanDao getCheckVerdBeanDao() {
        return checkVerdBeanDao;
    }

    public DataPackageDBeanDao getDataPackageDBeanDao() {
        return dataPackageDBeanDao;
    }

    public DeliveryListBeanDao getDeliveryListBeanDao() {
        return deliveryListBeanDao;
    }

    public DocumentBeanDao getDocumentBeanDao() {
        return documentBeanDao;
    }

    public FileBeanDao getFileBeanDao() {
        return fileBeanDao;
    }

    public PropertyBeanDao getPropertyBeanDao() {
        return propertyBeanDao;
    }

    public PropertyBeanXDao getPropertyBeanXDao() {
        return propertyBeanXDao;
    }

    public RegisterBeanDao getRegisterBeanDao() {
        return registerBeanDao;
    }

    public RelatedDocumentIdSetBeanDao getRelatedDocumentIdSetBeanDao() {
        return relatedDocumentIdSetBeanDao;
    }

    public TestTabBeanDao getTestTabBeanDao() {
        return testTabBeanDao;
    }

    public UnresolvedBeanDao getUnresolvedBeanDao() {
        return unresolvedBeanDao;
    }

}
