package com.example.acceptance2.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.acceptance2.greendao.bean.DataPackageDBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATA_PACKAGE_DBEAN".
*/
public class DataPackageDBeanDao extends AbstractDao<DataPackageDBean, Long> {

    public static final String TABLENAME = "DATA_PACKAGE_DBEAN";

    /**
     * Properties of entity DataPackageDBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UId = new Property(0, Long.class, "uId", true, "_id");
        public final static Property NamePackage = new Property(1, String.class, "namePackage", false, "NAME_PACKAGE");
        public final static Property UpLoadFile = new Property(2, String.class, "upLoadFile", false, "UP_LOAD_FILE");
        public final static Property Id = new Property(3, String.class, "id", false, "ID");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Code = new Property(5, String.class, "code", false, "CODE");
        public final static Property Type = new Property(6, String.class, "type", false, "TYPE");
        public final static Property ResponseUnit = new Property(7, String.class, "responseUnit", false, "RESPONSE_UNIT");
        public final static Property ModelCode = new Property(8, String.class, "modelCode", false, "MODEL_CODE");
        public final static Property ProductName = new Property(9, String.class, "productName", false, "PRODUCT_NAME");
        public final static Property ProductCode = new Property(10, String.class, "productCode", false, "PRODUCT_CODE");
        public final static Property ProductType = new Property(11, String.class, "productType", false, "PRODUCT_TYPE");
        public final static Property Batch = new Property(12, String.class, "batch", false, "BATCH");
        public final static Property Creator = new Property(13, String.class, "creator", false, "CREATOR");
        public final static Property CreateTime = new Property(14, String.class, "createTime", false, "CREATE_TIME");
        public final static Property ModelSeries = new Property(15, String.class, "modelSeries", false, "MODEL_SERIES");
        public final static Property ModelSeriesName = new Property(16, String.class, "modelSeriesName", false, "MODEL_SERIES_NAME");
        public final static Property PkgTemplateId = new Property(17, String.class, "pkgTemplateId", false, "PKG_TEMPLATE_ID");
        public final static Property LifecycleStateId = new Property(18, String.class, "lifecycleStateId", false, "LIFECYCLE_STATE_ID");
        public final static Property LifecycleStateIdentifier = new Property(19, String.class, "lifecycleStateIdentifier", false, "LIFECYCLE_STATE_IDENTIFIER");
        public final static Property BaseType = new Property(20, String.class, "baseType", false, "BASE_TYPE");
        public final static Property ModelSeriesId = new Property(21, String.class, "modelSeriesId", false, "MODEL_SERIES_ID");
        public final static Property RepositoryId = new Property(22, String.class, "repositoryId", false, "REPOSITORY_ID");
        public final static Property IsTemplate = new Property(23, String.class, "isTemplate", false, "IS_TEMPLATE");
        public final static Property OwnerId = new Property(24, String.class, "ownerId", false, "OWNER_ID");
        public final static Property ProductTypeValue = new Property(25, String.class, "productTypeValue", false, "PRODUCT_TYPE_VALUE");
        public final static Property ApplyCompany = new Property(26, String.class, "applyCompany", false, "APPLY_COMPANY");
        public final static Property AcceptorUnit = new Property(27, String.class, "acceptorUnit", false, "ACCEPTOR_UNIT");
        public final static Property Stage = new Property(28, String.class, "stage", false, "STAGE");
        public final static Property UniqueValue = new Property(29, String.class, "uniqueValue", false, "UNIQUE_VALUE");
        public final static Property VersionInfo = new Property(30, String.class, "versionInfo", false, "VERSION_INFO");
        public final static Property VersionInfo2 = new Property(31, String.class, "versionInfo2", false, "VERSION_INFO2");
    }


    public DataPackageDBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DataPackageDBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATA_PACKAGE_DBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uId
                "\"NAME_PACKAGE\" TEXT," + // 1: namePackage
                "\"UP_LOAD_FILE\" TEXT," + // 2: upLoadFile
                "\"ID\" TEXT," + // 3: id
                "\"NAME\" TEXT," + // 4: name
                "\"CODE\" TEXT," + // 5: code
                "\"TYPE\" TEXT," + // 6: type
                "\"RESPONSE_UNIT\" TEXT," + // 7: responseUnit
                "\"MODEL_CODE\" TEXT," + // 8: modelCode
                "\"PRODUCT_NAME\" TEXT," + // 9: productName
                "\"PRODUCT_CODE\" TEXT," + // 10: productCode
                "\"PRODUCT_TYPE\" TEXT," + // 11: productType
                "\"BATCH\" TEXT," + // 12: batch
                "\"CREATOR\" TEXT," + // 13: creator
                "\"CREATE_TIME\" TEXT," + // 14: createTime
                "\"MODEL_SERIES\" TEXT," + // 15: modelSeries
                "\"MODEL_SERIES_NAME\" TEXT," + // 16: modelSeriesName
                "\"PKG_TEMPLATE_ID\" TEXT," + // 17: pkgTemplateId
                "\"LIFECYCLE_STATE_ID\" TEXT," + // 18: lifecycleStateId
                "\"LIFECYCLE_STATE_IDENTIFIER\" TEXT," + // 19: lifecycleStateIdentifier
                "\"BASE_TYPE\" TEXT," + // 20: baseType
                "\"MODEL_SERIES_ID\" TEXT," + // 21: modelSeriesId
                "\"REPOSITORY_ID\" TEXT," + // 22: repositoryId
                "\"IS_TEMPLATE\" TEXT," + // 23: isTemplate
                "\"OWNER_ID\" TEXT," + // 24: ownerId
                "\"PRODUCT_TYPE_VALUE\" TEXT," + // 25: productTypeValue
                "\"APPLY_COMPANY\" TEXT," + // 26: applyCompany
                "\"ACCEPTOR_UNIT\" TEXT," + // 27: acceptorUnit
                "\"STAGE\" TEXT," + // 28: stage
                "\"UNIQUE_VALUE\" TEXT," + // 29: uniqueValue
                "\"VERSION_INFO\" TEXT," + // 30: versionInfo
                "\"VERSION_INFO2\" TEXT);"); // 31: versionInfo2
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATA_PACKAGE_DBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DataPackageDBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String namePackage = entity.getNamePackage();
        if (namePackage != null) {
            stmt.bindString(2, namePackage);
        }
 
        String upLoadFile = entity.getUpLoadFile();
        if (upLoadFile != null) {
            stmt.bindString(3, upLoadFile);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(6, code);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
 
        String responseUnit = entity.getResponseUnit();
        if (responseUnit != null) {
            stmt.bindString(8, responseUnit);
        }
 
        String modelCode = entity.getModelCode();
        if (modelCode != null) {
            stmt.bindString(9, modelCode);
        }
 
        String productName = entity.getProductName();
        if (productName != null) {
            stmt.bindString(10, productName);
        }
 
        String productCode = entity.getProductCode();
        if (productCode != null) {
            stmt.bindString(11, productCode);
        }
 
        String productType = entity.getProductType();
        if (productType != null) {
            stmt.bindString(12, productType);
        }
 
        String batch = entity.getBatch();
        if (batch != null) {
            stmt.bindString(13, batch);
        }
 
        String creator = entity.getCreator();
        if (creator != null) {
            stmt.bindString(14, creator);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(15, createTime);
        }
 
        String modelSeries = entity.getModelSeries();
        if (modelSeries != null) {
            stmt.bindString(16, modelSeries);
        }
 
        String modelSeriesName = entity.getModelSeriesName();
        if (modelSeriesName != null) {
            stmt.bindString(17, modelSeriesName);
        }
 
        String pkgTemplateId = entity.getPkgTemplateId();
        if (pkgTemplateId != null) {
            stmt.bindString(18, pkgTemplateId);
        }
 
        String lifecycleStateId = entity.getLifecycleStateId();
        if (lifecycleStateId != null) {
            stmt.bindString(19, lifecycleStateId);
        }
 
        String lifecycleStateIdentifier = entity.getLifecycleStateIdentifier();
        if (lifecycleStateIdentifier != null) {
            stmt.bindString(20, lifecycleStateIdentifier);
        }
 
        String baseType = entity.getBaseType();
        if (baseType != null) {
            stmt.bindString(21, baseType);
        }
 
        String modelSeriesId = entity.getModelSeriesId();
        if (modelSeriesId != null) {
            stmt.bindString(22, modelSeriesId);
        }
 
        String repositoryId = entity.getRepositoryId();
        if (repositoryId != null) {
            stmt.bindString(23, repositoryId);
        }
 
        String isTemplate = entity.getIsTemplate();
        if (isTemplate != null) {
            stmt.bindString(24, isTemplate);
        }
 
        String ownerId = entity.getOwnerId();
        if (ownerId != null) {
            stmt.bindString(25, ownerId);
        }
 
        String productTypeValue = entity.getProductTypeValue();
        if (productTypeValue != null) {
            stmt.bindString(26, productTypeValue);
        }
 
        String applyCompany = entity.getApplyCompany();
        if (applyCompany != null) {
            stmt.bindString(27, applyCompany);
        }
 
        String acceptorUnit = entity.getAcceptorUnit();
        if (acceptorUnit != null) {
            stmt.bindString(28, acceptorUnit);
        }
 
        String stage = entity.getStage();
        if (stage != null) {
            stmt.bindString(29, stage);
        }
 
        String uniqueValue = entity.getUniqueValue();
        if (uniqueValue != null) {
            stmt.bindString(30, uniqueValue);
        }
 
        String versionInfo = entity.getVersionInfo();
        if (versionInfo != null) {
            stmt.bindString(31, versionInfo);
        }
 
        String versionInfo2 = entity.getVersionInfo2();
        if (versionInfo2 != null) {
            stmt.bindString(32, versionInfo2);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DataPackageDBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String namePackage = entity.getNamePackage();
        if (namePackage != null) {
            stmt.bindString(2, namePackage);
        }
 
        String upLoadFile = entity.getUpLoadFile();
        if (upLoadFile != null) {
            stmt.bindString(3, upLoadFile);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(4, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(6, code);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
 
        String responseUnit = entity.getResponseUnit();
        if (responseUnit != null) {
            stmt.bindString(8, responseUnit);
        }
 
        String modelCode = entity.getModelCode();
        if (modelCode != null) {
            stmt.bindString(9, modelCode);
        }
 
        String productName = entity.getProductName();
        if (productName != null) {
            stmt.bindString(10, productName);
        }
 
        String productCode = entity.getProductCode();
        if (productCode != null) {
            stmt.bindString(11, productCode);
        }
 
        String productType = entity.getProductType();
        if (productType != null) {
            stmt.bindString(12, productType);
        }
 
        String batch = entity.getBatch();
        if (batch != null) {
            stmt.bindString(13, batch);
        }
 
        String creator = entity.getCreator();
        if (creator != null) {
            stmt.bindString(14, creator);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(15, createTime);
        }
 
        String modelSeries = entity.getModelSeries();
        if (modelSeries != null) {
            stmt.bindString(16, modelSeries);
        }
 
        String modelSeriesName = entity.getModelSeriesName();
        if (modelSeriesName != null) {
            stmt.bindString(17, modelSeriesName);
        }
 
        String pkgTemplateId = entity.getPkgTemplateId();
        if (pkgTemplateId != null) {
            stmt.bindString(18, pkgTemplateId);
        }
 
        String lifecycleStateId = entity.getLifecycleStateId();
        if (lifecycleStateId != null) {
            stmt.bindString(19, lifecycleStateId);
        }
 
        String lifecycleStateIdentifier = entity.getLifecycleStateIdentifier();
        if (lifecycleStateIdentifier != null) {
            stmt.bindString(20, lifecycleStateIdentifier);
        }
 
        String baseType = entity.getBaseType();
        if (baseType != null) {
            stmt.bindString(21, baseType);
        }
 
        String modelSeriesId = entity.getModelSeriesId();
        if (modelSeriesId != null) {
            stmt.bindString(22, modelSeriesId);
        }
 
        String repositoryId = entity.getRepositoryId();
        if (repositoryId != null) {
            stmt.bindString(23, repositoryId);
        }
 
        String isTemplate = entity.getIsTemplate();
        if (isTemplate != null) {
            stmt.bindString(24, isTemplate);
        }
 
        String ownerId = entity.getOwnerId();
        if (ownerId != null) {
            stmt.bindString(25, ownerId);
        }
 
        String productTypeValue = entity.getProductTypeValue();
        if (productTypeValue != null) {
            stmt.bindString(26, productTypeValue);
        }
 
        String applyCompany = entity.getApplyCompany();
        if (applyCompany != null) {
            stmt.bindString(27, applyCompany);
        }
 
        String acceptorUnit = entity.getAcceptorUnit();
        if (acceptorUnit != null) {
            stmt.bindString(28, acceptorUnit);
        }
 
        String stage = entity.getStage();
        if (stage != null) {
            stmt.bindString(29, stage);
        }
 
        String uniqueValue = entity.getUniqueValue();
        if (uniqueValue != null) {
            stmt.bindString(30, uniqueValue);
        }
 
        String versionInfo = entity.getVersionInfo();
        if (versionInfo != null) {
            stmt.bindString(31, versionInfo);
        }
 
        String versionInfo2 = entity.getVersionInfo2();
        if (versionInfo2 != null) {
            stmt.bindString(32, versionInfo2);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DataPackageDBean readEntity(Cursor cursor, int offset) {
        DataPackageDBean entity = new DataPackageDBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // namePackage
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // upLoadFile
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // code
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // type
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // responseUnit
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // modelCode
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // productName
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // productCode
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // productType
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // batch
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // creator
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // createTime
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // modelSeries
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // modelSeriesName
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // pkgTemplateId
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // lifecycleStateId
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // lifecycleStateIdentifier
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // baseType
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // modelSeriesId
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // repositoryId
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // isTemplate
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // ownerId
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // productTypeValue
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // applyCompany
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // acceptorUnit
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // stage
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // uniqueValue
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // versionInfo
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31) // versionInfo2
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DataPackageDBean entity, int offset) {
        entity.setUId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNamePackage(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUpLoadFile(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setResponseUnit(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setModelCode(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setProductName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setProductCode(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setProductType(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setBatch(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setCreator(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCreateTime(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setModelSeries(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setModelSeriesName(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPkgTemplateId(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setLifecycleStateId(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setLifecycleStateIdentifier(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setBaseType(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setModelSeriesId(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setRepositoryId(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setIsTemplate(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setOwnerId(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setProductTypeValue(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setApplyCompany(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setAcceptorUnit(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setStage(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setUniqueValue(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setVersionInfo(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setVersionInfo2(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DataPackageDBean entity, long rowId) {
        entity.setUId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DataPackageDBean entity) {
        if(entity != null) {
            return entity.getUId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DataPackageDBean entity) {
        return entity.getUId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
